<?php
/*
 * cookies.inc
 *
 * Copyright (c) 2015 DOXEL SA - http://doxel.ch
 * Please read <http://doxel.ch/license> for more information.
 *
 * Author(s):
 *
 *      Rurik Bugdanov <rurik.bugdanov@alsenet.com>
 *
 * This file is part of the DOXEL project <http://doxel.ch>.
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 * Additional Terms:
 *
 *      You are required to preserve legal notices and author attributions in
 *      that material or in the Appropriate Legal Notices displayed by works
 *      containing it.
 *
 *      You are required to attribute the work as explained in the "Usage and
 *      Attribution" section of <http://doxel.ch/license>.
 */

if (isset($_COOKIE['token'])) {
  $token=$_COOKIE['token'];
} else {
  $length=16;
  $token=bin2hex(openssl_random_pseudo_bytes($length));
  setcookie( "token", $token, pow(2,31) /* 2038-01-19 04:14:07 */ );
}

if (isset($_COOKIE['fingerprint'])) {
  $fingerprint=$_COOKIE['fingerprint'];
}

?>
