<!DOCTYPE html>
<html>
  <head>
    <meta http-equiv="content-type" content="text/html; charset=UTF-8"/>
    <title>Upload Pictures</title>
    <meta name="viewport" content="width=device-width,initial-scale=1,user-scalable=no,minimum-scale=1,maximum-scale=1" />
    <link rel="stylesheet" type="text/css" href="Font-Awesome/css/font-awesome.css" />
    <link rel="stylesheet" href="js/thirdparty/jquery-ui/themes/base/jquery-ui.css" type="text/css" />
    <link rel="stylesheet" href="js/thirdparty/plupload/js/jquery.ui.plupload/css/jquery.ui.plupload.css" type="text/css" />

    <link rel="stylesheet" type="text/css" href="css/doxel-webapp.css">
    <script type="text/javascript" src="js/thirdparty/jquery-2.1.4.js"></script>
    <script type="text/javascript" src="js/thirdparty/jquery-ui/jquery-ui.js"></script>
    <script type="text/javascript" src="js/thirdparty/blueimp-load-image/js/load-image.js"></script>
    <script type="text/javascript" src="js/thirdparty/blueimp-load-image/js/load-image-meta.js"></script>
    <script type="text/javascript" src="js/thirdparty/blueimp-load-image/js/load-image-orientation.js"></script>    
    <script type="text/javascript" src="js/thirdparty/blueimp-load-image/js/load-image-ios.js"></script>
    <script type="text/javascript" src="js/thirdparty/blueimp-load-image/js/load-image-exif.js"></script>
    <script type="text/javascript" src="js/thirdparty/blueimp-load-image/js/load-image-exif-map.js"></script>
    <script type="text/javascript" src="js/thirdparty/plupload/js/moxie.js"></script>
    <script type="text/javascript" src="js/thirdparty/plupload/js/plupload.dev.js"></script>
    <script type="text/javascript" src="js/thirdparty/plupload/js/jquery.ui.plupload/jquery.ui.plupload.js"></script>
    <script type="text/javascript" src="js/thirdparty/jquery-cookie/src/jquery.cookie.js"></script>
    <script type="text/javascript" src="js/thirdparty/fingerprintjs2/fingerprint2.js"></script>
    <script type="text/javascript" src="js/view.js"></script>
    <script type="text/javascript" src="js/doxel-webapp.js"></script>
  </head>
  <body class="disable-selection">
  </body>
</html>
